export const RestaurantErrorCode = {
  RESTAURANT_NOT_FOUND: '',
  RESTAURANT_MENU_ALREADY_EXISTS: '',
  RESTAURANT_STORE_ALREADY_EXISTS: '',
  RESTAURANT_STORE_NOT_FOUND: '',
  RESTAURANT_STORE_TABLE_ALREADY_EXISTS: '',
  RESTAURANT_STORE_TABLE_NOT_FOUND: '',
} as const;
