export const RestaurantErrorCode = {
  RESTAURANT_NOT_FOUND: '',
  RESTAURANT_MENU_ALREADY_EXISTS: '',
  RESTAURANT_OUTLET_ALREADY_EXISTS: '',
  RESTAURANT_OUTLET_NOT_FOUND: '',
  RESTAURANT_OUTLET_TABLE_ALREADY_EXISTS: '',
  RESTAURANT_OUTLET_TABLE_NOT_FOUND: '',
} as const;
