export const RestaurantErrorCode = {
  RESTAURANT_NOT_FOUND: '',
  RESTAURANT_MENU_ALREADY_EXISTS: '',
  RESTAURANT_OUTLET_ALREADY_EXISTS: '',
  RESTAURANT_OUTLET_DOES_NOT_EXISTS: '',
  RESTAURANT_OUTLET_TABLE_ALREADY_EXISTS: '',
  RESTAURANT_OUTLET_TABLE_DOES_NOT_EXISTS: '',
} as const;
