export const MenuErrorCode = {
  MENU_NOT_FOUND: '2000',
  MENU_CATEGORY_NAME_ALREADY_EXISTS: '',
  MENU_CATEGORY_NOT_FOUND: '',
  MENU_CATEGORY_ITEM_ALREADY_EXISTS: '',
  MENU_CATEGORY_ITEM_NOT_FOUND: '',
  MENU_ITEM_NAME_ALREADY_EXISTS: '',
  MENU_ITEM_NOT_FOUND: '',
  MENU_MODIFIER_NAME_ALREADY_EXISTS: '',
  MENU_MODIFIER_NOT_FOUND: '',
} as const;
